services:
  mysql:
    build: ./mysql
    container_name: mysql
    env_file:
      - ./mysql/db.env 
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306
  java:
    image: openjdk:15
    container_name: java
    env_file:
      - ./mysql/db.env
    tty: true
    working_dir: /app
    volumes:
      - ../test:/app
    ports:
      - 8080:8080
    depends_on:
      - mysql

volumes:
  db-store: